

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Labs : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Labs entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Labs()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Labs(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Labs> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Labs.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Labs_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Labs_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LabDate
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Fingers
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Fingers);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Fingers, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fingers_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fingers_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fingers_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> WBC
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.WBC);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.WBC, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WBC_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WBC_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WBC_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Limbs
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Limbs);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Limbs, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Limbs_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Limbs_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Limbs_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Person Person
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Person_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Person_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Person_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Labs,
                global::LightSwitchApplication.Labs.DetailsClass,
                global::LightSwitchApplication.Labs.DetailsClass.IImplementation,
                global::LightSwitchApplication.Labs.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>.Entry
                __LabsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>.Entry(
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_CreateNew,
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_Created,
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Labs __Labs_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Labs> es)
            {
                return new global::LightSwitchApplication.Labs(es);
            }
            private static void __Labs_Created(global::LightSwitchApplication.Labs e)
            {
                e.Labs_Created();
            }
            private static bool __Labs_AllowSaveWithErrors(global::LightSwitchApplication.Labs e)
            {
                bool result = false;
                e.Labs_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Labs.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime> LabDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>> Fingers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Fingers) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>> WBC
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.WBC) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>> Limbs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Limbs) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person> Person
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.DateTime LabDate { get; set; }
                new global::System.Nullable<int> Fingers { get; set; }
                new global::System.Nullable<decimal> WBC { get; set; }
                new global::System.Nullable<int> Limbs { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Person { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Entry
                    LabDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Entry(
                        "LabDate",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_OnValueChanged);
                private static void _LabDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._LabDate, sf);
                }
                private static bool _LabDate_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.LabDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _LabDate_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LabDate_Validate(r);
                }
                private static global::System.DateTime _LabDate_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.LabDate;
                }
                private static void _LabDate_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.LabDate = global::LightSwitchApplication.Labs.DetailsClass.TruncateDate(v);
                }
                private static void _LabDate_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.LabDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Entry
                    Fingers = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Fingers",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Fingers_OnValueChanged);
                private static void _Fingers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Fingers, sf);
                }
                private static bool _Fingers_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Fingers_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fingers_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fingers_Validate(r);
                }
                private static global::System.Nullable<int> _Fingers_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Fingers;
                }
                private static void _Fingers_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Fingers = v;
                }
                private static void _Fingers_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Fingers_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>>.Entry
                    WBC = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "WBC",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._WBC_OnValueChanged);
                private static void _WBC_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._WBC, sf);
                }
                private static bool _WBC_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.WBC_IsReadOnly(ref result);
                    return result;
                }
                private static void _WBC_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.WBC_Validate(r);
                }
                private static global::System.Nullable<decimal> _WBC_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.WBC;
                }
                private static void _WBC_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.WBC = v;
                }
                private static void _WBC_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.WBC_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Entry
                    Limbs = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Limbs",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Limbs_OnValueChanged);
                private static void _Limbs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Limbs, sf);
                }
                private static bool _Limbs_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Limbs_IsReadOnly(ref result);
                    return result;
                }
                private static void _Limbs_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Limbs_Validate(r);
                }
                private static global::System.Nullable<int> _Limbs_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Limbs;
                }
                private static void _Limbs_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Limbs = v;
                }
                private static void _Limbs_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Limbs_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person>.Entry
                    Person = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person>.Entry(
                        "Person",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_GetCoreImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_Refresh,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Person_OnValueChanged);
                private static void _Person_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Person, sf);
                }
                private static bool _Person_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Person_IsReadOnly(ref result);
                    return result;
                }
                private static void _Person_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Person_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Person_GetCoreImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Person;
                }
                private static global::LightSwitchApplication.Person _Person_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Person, global::LightSwitchApplication.Person.DetailsClass>(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person, ref d._Person);
                }
                private static void _Person_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::LightSwitchApplication.Person v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person, ref d._Person, (i, ev) => i.Person = ev, v);
                }
                private static void _Person_Refresh(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Person, ref d._Person);
                }
                private static void _Person_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Person_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Data _LabDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Data _Fingers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<decimal>>.Data _WBC;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.Nullable<int>>.Data _Limbs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Person>.Data _Person;
            
        }
    
        #endregion
    }
    
    #endregion
}
