//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class SearchPeople
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchPeople() : base("LightSwitchApplication.DesktopClient:SearchPeople")
        {
            global::LightSwitchApplication.SearchPeople.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchPeople CreateInstance()
        {
            return new global::LightSwitchApplication.SearchPeople(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPeople_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void People_SelectionChanged();

        partial void People_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void People_Loaded(bool succeeded);

        /// <summary>
        /// Gets the People visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Person> People
        {
            get
            {
                return global::LightSwitchApplication.SearchPeople.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties.People);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void People_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySet, global::LightSwitchApplication.SearchPeople.DetailsClass.CommandSet, global::LightSwitchApplication.SearchPeople.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties.People;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>.Entry
                __SearchPeopleEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeCreated,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeActivated,
                    global::LightSwitchApplication.SearchPeople.DetailsClass.__SearchPeople_InvokeSaveErrorEvent);
            private static void __SearchPeople_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchPeople s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchPeople_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchPeople_InvokeSavingEvent(global::LightSwitchApplication.SearchPeople s)
            {
                bool handled = false;
                s.SearchPeople_Saving(ref handled);
                return handled;
            }
            private static void __SearchPeople_InvokeSavedEvent(global::LightSwitchApplication.SearchPeople s)
            {
                s.SearchPeople_Saved();
            }
            private static bool __SearchPeople_InvokeClosingEvent(global::LightSwitchApplication.SearchPeople s)
            {
                bool cancel = false;
                s.SearchPeople_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchPeople_InvokeCreated(global::LightSwitchApplication.SearchPeople s)
            {
                s.SearchPeople_Created();
            }
            private static void __SearchPeople_InvokeActivated(global::LightSwitchApplication.SearchPeople s)
            {
                s.SearchPeople_Activated();
            }
            private static bool __SearchPeople_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchPeople s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchPeople_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchPeople.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchPeople.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PeopleQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.People;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person>.Data _People;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person> People
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person>)base.GetItem(global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties.People);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person>.Entry
                    People = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person>.Entry(
                        "People",
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_Stub,
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_Validate,
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_CreateQuery,
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_SelectionChanged,
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_OnCollectionChanged,
                        global::LightSwitchApplication.SearchPeople.DetailsClass.PropertySetProperties._People_OnLoaded);
                private static void _People_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchPeople.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPeople, global::LightSwitchApplication.SearchPeople.DetailsClass, global::LightSwitchApplication.Person>.Data> c, global::LightSwitchApplication.SearchPeople.DetailsClass d, object sf)
                {
                    c(d, ref d._People, sf);
                }
                private static void _People_Validate(global::LightSwitchApplication.SearchPeople s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.People_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _People_CreateQuery(global::LightSwitchApplication.SearchPeople.DetailsClass d, object[] args)
                {
                    return d.PeopleQuery();
                }
                private static void _People_SelectionChanged(global::LightSwitchApplication.SearchPeople s)
                {
                    s.People_SelectionChanged();
                }
                private static void _People_OnCollectionChanged(global::LightSwitchApplication.SearchPeople s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.People_Changed(e);
                }
                private static void _People_OnLoaded(global::LightSwitchApplication.SearchPeople s, bool succeeded)
                {
                    s.People_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class PersonDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private PersonDetail(int PersonId) : base("LightSwitchApplication.DesktopClient:PersonDetail")
        {
                this.PersonId = PersonId;
            global::LightSwitchApplication.PersonDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static PersonDetail CreateInstance(int PersonId)
        {
            return new global::LightSwitchApplication.PersonDetail(
                        PersonId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Person_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Person_Loaded(bool succeeded);

        partial void PersonId_Changed();

        partial void LabsCollection_SelectionChanged();

        partial void LabsCollection_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsCollection_Loaded(bool succeeded);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Person Person
        {
            get
            {
                return global::LightSwitchApplication.PersonDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.Person);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Person_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonId
        {
            get 
            {
                return global::LightSwitchApplication.PersonDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.PersonId);
            }
            set
            {
                global::LightSwitchApplication.PersonDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.PersonId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the LabsCollection visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Labs> LabsCollection
        {
            get
            {
                return global::LightSwitchApplication.PersonDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.LabsCollection);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsCollection_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySet, global::LightSwitchApplication.PersonDetail.DetailsClass.CommandSet, global::LightSwitchApplication.PersonDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.Person;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>.Entry
                __PersonDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeCreated,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeActivated,
                    global::LightSwitchApplication.PersonDetail.DetailsClass.__PersonDetail_InvokeSaveErrorEvent);
            private static void __PersonDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.PersonDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.PersonDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __PersonDetail_InvokeSavingEvent(global::LightSwitchApplication.PersonDetail s)
            {
                bool handled = false;
                s.PersonDetail_Saving(ref handled);
                return handled;
            }
            private static void __PersonDetail_InvokeSavedEvent(global::LightSwitchApplication.PersonDetail s)
            {
                s.PersonDetail_Saved();
            }
            private static bool __PersonDetail_InvokeClosingEvent(global::LightSwitchApplication.PersonDetail s)
            {
                bool cancel = false;
                s.PersonDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __PersonDetail_InvokeCreated(global::LightSwitchApplication.PersonDetail s)
            {
                s.PersonDetail_Created();
            }
            private static void __PersonDetail_InvokeActivated(global::LightSwitchApplication.PersonDetail s)
            {
                s.PersonDetail_Activated();
            }
            private static bool __PersonDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.PersonDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.PersonDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.PersonDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.PersonDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable LabsCollectionQuery()
            {
                if (this.Screen.Person == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Labs> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Labs>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Person.Details.Properties.LabsCollection).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    loader,
                    "Person");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person>.Data _Person;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int>.Data _PersonId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs>.Data _LabsCollection;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person> Person
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person>)base.GetItem(global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.Person);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int> PersonId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.PersonId);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs> LabsCollection
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs>)base.GetItem(global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties.LabsCollection);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person>.Entry
                    Person = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person>.Entry(
                        "Person",
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._Person_Stub,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._Person_Validate,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._Person_CreateQuery,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._Person_OnValueChanged,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._Person_OnLoaded);
                private static void _Person_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PersonDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Person>.Data> c, global::LightSwitchApplication.PersonDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Person, sf);
                }
                private static void _Person_Validate(global::LightSwitchApplication.PersonDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Person_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Person_CreateQuery(global::LightSwitchApplication.PersonDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Person_OnValueChanged(global::LightSwitchApplication.PersonDetail s)
                {
                    s.Person_Changed();
                }

                private static void _Person_OnLoaded(global::LightSwitchApplication.PersonDetail s, bool succeeded)
                {
                    s.Person_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int>.Entry
                    PersonId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int>.Entry(
                        "PersonId",
                        false,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._PersonId_Stub,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._PersonId_Validate,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._PersonId_OnValueChanged);
                private static void _PersonId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PersonDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.PersonDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PersonId, sf);
                }
                private static void _PersonId_Validate(global::LightSwitchApplication.PersonDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.PersonId_Validate(r);
                }
                private static void _PersonId_OnValueChanged(global::LightSwitchApplication.PersonDetail s)
                {
                    s.PersonId_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs>.Entry
                    LabsCollection = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs>.Entry(
                        "LabsCollection",
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_Stub,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_Validate,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_CreateQuery,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_SelectionChanged,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_OnCollectionChanged,
                        global::LightSwitchApplication.PersonDetail.DetailsClass.PropertySetProperties._LabsCollection_OnLoaded);
                private static void _LabsCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PersonDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PersonDetail, global::LightSwitchApplication.PersonDetail.DetailsClass, global::LightSwitchApplication.Labs>.Data> c, global::LightSwitchApplication.PersonDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._LabsCollection, sf);
                }
                private static void _LabsCollection_Validate(global::LightSwitchApplication.PersonDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.LabsCollection_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _LabsCollection_CreateQuery(global::LightSwitchApplication.PersonDetail.DetailsClass d, object[] args)
                {
                    return d.LabsCollectionQuery();
                }
                private static void _LabsCollection_SelectionChanged(global::LightSwitchApplication.PersonDetail s)
                {
                    s.LabsCollection_SelectionChanged();
                }
                private static void _LabsCollection_OnCollectionChanged(global::LightSwitchApplication.PersonDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.LabsCollection_Changed(e);
                }
                private static void _LabsCollection_OnLoaded(global::LightSwitchApplication.PersonDetail s, bool succeeded)
                {
                    s.LabsCollection_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class EditablePeopleGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditablePeopleGrid() : base("LightSwitchApplication.DesktopClient:EditablePeopleGrid")
        {
            global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditablePeopleGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditablePeopleGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePeopleGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void People_SelectionChanged();

        partial void People_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void People_Loaded(bool succeeded);

        /// <summary>
        /// Gets the People visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Person> People
        {
            get
            {
                return global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties.People);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void People_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties.People;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>.Entry
                __EditablePeopleGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeCreated,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeActivated,
                    global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.__EditablePeopleGrid_InvokeSaveErrorEvent);
            private static void __EditablePeopleGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditablePeopleGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditablePeopleGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditablePeopleGrid_InvokeSavingEvent(global::LightSwitchApplication.EditablePeopleGrid s)
            {
                bool handled = false;
                s.EditablePeopleGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditablePeopleGrid_InvokeSavedEvent(global::LightSwitchApplication.EditablePeopleGrid s)
            {
                s.EditablePeopleGrid_Saved();
            }
            private static bool __EditablePeopleGrid_InvokeClosingEvent(global::LightSwitchApplication.EditablePeopleGrid s)
            {
                bool cancel = false;
                s.EditablePeopleGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditablePeopleGrid_InvokeCreated(global::LightSwitchApplication.EditablePeopleGrid s)
            {
                s.EditablePeopleGrid_Created();
            }
            private static void __EditablePeopleGrid_InvokeActivated(global::LightSwitchApplication.EditablePeopleGrid s)
            {
                s.EditablePeopleGrid_Activated();
            }
            private static bool __EditablePeopleGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditablePeopleGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditablePeopleGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PeopleQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.People;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person>.Data _People;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person> People
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person>)base.GetItem(global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties.People);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person>.Entry
                    People = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person>.Entry(
                        "People",
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_Stub,
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_Validate,
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_CreateQuery,
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_SelectionChanged,
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_OnCollectionChanged,
                        global::LightSwitchApplication.EditablePeopleGrid.DetailsClass.PropertySetProperties._People_OnLoaded);
                private static void _People_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePeopleGrid, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass, global::LightSwitchApplication.Person>.Data> c, global::LightSwitchApplication.EditablePeopleGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._People, sf);
                }
                private static void _People_Validate(global::LightSwitchApplication.EditablePeopleGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.People_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _People_CreateQuery(global::LightSwitchApplication.EditablePeopleGrid.DetailsClass d, object[] args)
                {
                    return d.PeopleQuery();
                }
                private static void _People_SelectionChanged(global::LightSwitchApplication.EditablePeopleGrid s)
                {
                    s.People_SelectionChanged();
                }
                private static void _People_OnCollectionChanged(global::LightSwitchApplication.EditablePeopleGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.People_Changed(e);
                }
                private static void _People_OnLoaded(global::LightSwitchApplication.EditablePeopleGrid s, bool succeeded)
                {
                    s.People_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class EditableLabsSetGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditableLabsSetGrid() : base("LightSwitchApplication.DesktopClient:EditableLabsSetGrid")
        {
            global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditableLabsSetGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditableLabsSetGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableLabsSetGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void LabsSet_SelectionChanged();

        partial void LabsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the LabsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Labs> LabsSet
        {
            get
            {
                return global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties.LabsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties.LabsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>.Entry
                __EditableLabsSetGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeCreated,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeActivated,
                    global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.__EditableLabsSetGrid_InvokeSaveErrorEvent);
            private static void __EditableLabsSetGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditableLabsSetGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditableLabsSetGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditableLabsSetGrid_InvokeSavingEvent(global::LightSwitchApplication.EditableLabsSetGrid s)
            {
                bool handled = false;
                s.EditableLabsSetGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditableLabsSetGrid_InvokeSavedEvent(global::LightSwitchApplication.EditableLabsSetGrid s)
            {
                s.EditableLabsSetGrid_Saved();
            }
            private static bool __EditableLabsSetGrid_InvokeClosingEvent(global::LightSwitchApplication.EditableLabsSetGrid s)
            {
                bool cancel = false;
                s.EditableLabsSetGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditableLabsSetGrid_InvokeCreated(global::LightSwitchApplication.EditableLabsSetGrid s)
            {
                s.EditableLabsSetGrid_Created();
            }
            private static void __EditableLabsSetGrid_InvokeActivated(global::LightSwitchApplication.EditableLabsSetGrid s)
            {
                s.EditableLabsSetGrid_Activated();
            }
            private static bool __EditableLabsSetGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditableLabsSetGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditableLabsSetGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable LabsSetQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.LabsSet,
                    "Person");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs>.Data _LabsSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs> LabsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs>)base.GetItem(global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties.LabsSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs>.Entry
                    LabsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs>.Entry(
                        "LabsSet",
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_Stub,
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_Validate,
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_CreateQuery,
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_SelectionChanged,
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_OnCollectionChanged,
                        global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass.PropertySetProperties._LabsSet_OnLoaded);
                private static void _LabsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableLabsSetGrid, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass, global::LightSwitchApplication.Labs>.Data> c, global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._LabsSet, sf);
                }
                private static void _LabsSet_Validate(global::LightSwitchApplication.EditableLabsSetGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.LabsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _LabsSet_CreateQuery(global::LightSwitchApplication.EditableLabsSetGrid.DetailsClass d, object[] args)
                {
                    return d.LabsSetQuery();
                }
                private static void _LabsSet_SelectionChanged(global::LightSwitchApplication.EditableLabsSetGrid s)
                {
                    s.LabsSet_SelectionChanged();
                }
                private static void _LabsSet_OnCollectionChanged(global::LightSwitchApplication.EditableLabsSetGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.LabsSet_Changed(e);
                }
                private static void _LabsSet_OnLoaded(global::LightSwitchApplication.EditableLabsSetGrid s, bool succeeded)
                {
                    s.LabsSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
